// Database delle aviostrutture del Friuli Venezia Giulia (aeroporti civili
// e militari, aviosuperfici, campi volo, piste dismesse) — sezione
// Aviazione, richiesta dall'utente il 25/08/2026.
//
// Fonte: webaai.it (World Airfields Directory / WebAAI), pagina elenco
// https://webaai.it/it/aviostrutture/friuli_venezia_giulia (27 strutture
// elencate al momento della raccolta, 25/08/2026) più le rispettive pagine
// di dettaglio per ciascuna struttura con link (26 su 27 — "Aviosuperficie
// Enemonzo" risulta solo nell'elenco, con dati ENAC, senza una pagina di
// dettaglio propria su webaai.it).
//
// NOTE:
//
// 1) **Dati statici, non un modulo ingerito**: a differenza di Calcio/
//    Basket/Baseball/Tennis/Sci, questo NON è un dato che cambia di
//    frequente (sono strutture fisiche, non classifiche/calendari
//    sportivi) — nessuna funzione ingestXxx() in ingest-light.mjs, nessuna
//    tabella Supabase. Popolato una tantum leggendo ogni pagina via
//    WebFetch (l'host webaai.it, come comitati.fisi.org e l'host Tennis,
//    risulta bloccato dalla allowlist di rete di questo sandbox per un
//    fetch diretto — stesso limite già documentato per Tennis/Sci — ma
//    WebFetch stesso ha funzionato, restituendo i dati reali invece del
//    solito "nessun markup" che si ha con pagine JS/AJAX-dipendenti: la
//    pagina è HTML statico lato server). Da aggiornare manualmente in una
//    sessione futura se l'utente segnala nuove strutture o dati cambiati —
//    non c'è ancora un meccanismo automatico.
//
// 2) **Molti dati sono dietro un paywall "Premium"** sul sito sorgente:
//    contatti, orari di apertura, frequenze radio, lunghezza/orientamento/
//    superficie della pista, foto, mappe di avvicinamento. Qui sono
//    inclusi SOLO i campi pubblicamente visibili senza login — vedi il
//    tipo `Aviostruttura` sotto per l'elenco esatto.
//
// 3) **Incongruenza segnalata, non risolta**: la pagina elenco dichiara un
//    totale di "33 strutture", ma la tabella/elenco effettivo mostra 27
//    voci distinte (verificato con due letture indipendenti della stessa
//    pagina) — possibile che alcune strutture censite da ENAC ma non
//    ancora schedate da webaai.it non compaiano nell'elenco pubblico.
//    Usati i 27 confermati, senza inventare le altre 6.
//
// 4) **Il prefisso del "codice avioportolano" non è un indicatore
//    affidabile di provincia** (stessa lezione già annotata per altri
//    parametri/classi non documentati — vedi README/doc di progetto):
//    "Casarsa della Delizia" ha codice `UD19` (prefisso Udine) ma il
//    comune è amministrativamente in provincia di Pordenone — corretto
//    qui a `provincia: "PN"`, che è il dato geograficamente vero,
//    ignorando il prefisso del codice.
//
// 5) **Coordinate**: la fonte usa due notazioni diverse a seconda della
//    pagina (gradi+minuti decimali in formato aeronautico, es.
//    "4549.650N", oppure gradi/minuti/secondi, es. "45°49'39\"N") —
//    convertite qui una volta per tutte in gradi decimali (`lat`/`lon`),
//    verificate contro le coordinate reali note di Trieste Airport (LIPQ)
//    e dell'aeroporto di Rivolto come controllo di sanità.
//
// 6) **"Ultimo aggiornamento" (`aggiornatoFonte`) è per singola struttura**,
//    dichiarato da webaai.it sulla sua pagina di dettaglio — non è la data
//    in cui abbiamo raccolto il dato noi (25/08/2026), varia molto da
//    struttura a struttura (dal 2019 al 2026).

export type CategoriaAviostruttura =
  | "aeroporto-civile"
  | "aeroporto-militare"
  | "aviosuperficie"
  | "campo-volo"
  | "pista-dismessa";

export type Aviostruttura = {
  nome: string;
  urlFonte: string | null; // pagina di dettaglio su webaai.it, null se non esiste
  comune: string;
  localita: string | null; // frazione/toponimo locale, se diverso dal comune
  provincia: "UD" | "GO" | "PN";
  tipo: string; // descrizione testuale così come mostrata dalla fonte
  categoria: CategoriaAviostruttura; // stessa info di `tipo`, normalizzata per i filtri della pagina
  codice: string | null; // codice avioportolano ENAC (es. "UD12") — vedi nota 4 sopra
  icao: string | null;
  indirizzo: string | null;
  cap: string | null;
  lat: number | null;
  lon: number | null;
  quotaM: number | null;
  piste: number | null;
  categorieVolo: string[]; // abilitazioni: General aviation, Advanced UL, Basic UL, Gliders, Helicopters
  enacDirezione: string | null;
  fascicolo: string | null;
  aggiornatoFonte: string | null; // vedi nota 6 sopra
};

export const AVIOSTRUTTURE: Aviostruttura[] = [
  {
    nome: "Al Casale",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/al-casale_UD12",
    comune: "Codroipo",
    localita: null,
    provincia: "UD",
    tipo: "Aviosuperficie",
    categoria: "aviosuperficie",
    codice: "UD12",
    icao: "LIPT",
    indirizzo: "Casali Loreto, 3",
    cap: "33033",
    lat: 45.984822,
    lon: 12.923569,
    quotaM: null,
    piste: 1,
    categorieVolo: ["General aviation", "Advanced UL", "Basic UL"],
    enacDirezione: "Nord-Est",
    fascicolo: "5.1.8.1_2024_85",
    aggiornatoFonte: "2026-05-14",
  },
  {
    nome: "Al Ranch",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/al-ranch_UD02",
    comune: "Bertiolo",
    localita: null,
    provincia: "UD",
    tipo: "Campo volo (privato)",
    categoria: "campo-volo",
    codice: "UD02",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.9235,
    lon: 13.035667,
    quotaM: 20,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2019-01-18",
  },
  {
    nome: "Ali Friuli",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/ali-friuli_UD01",
    comune: "Cividale del Friuli",
    localita: "Gradaria",
    provincia: "UD",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "UD01",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 46.05695,
    lon: 13.426333,
    quotaM: 114,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2025-01-15",
  },
  {
    nome: "Always",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/always_UD04",
    comune: "Povoletto",
    localita: "Primulacco",
    provincia: "UD",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "UD04",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 46.133467,
    lon: 13.27825,
    quotaM: 142,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-07-09",
  },
  {
    nome: "AS77",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/as77_UD20",
    comune: "Mortegliano",
    localita: null,
    provincia: "UD",
    tipo: "Campo volo (privato)",
    categoria: "campo-volo",
    codice: "UD20",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.961433,
    lon: 13.2044,
    quotaM: 43,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2023-03-26",
  },
  {
    nome: "Aviano",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/aviano_PN07",
    comune: "Aviano",
    localita: null,
    provincia: "PN",
    tipo: "Aeroporto militare (asfaltato)",
    categoria: "aeroporto-militare",
    codice: "PN07",
    icao: "LIPA",
    indirizzo: null,
    cap: null,
    lat: 46.03,
    lon: 12.598883,
    quotaM: 126,
    piste: 1,
    categorieVolo: [],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2024-10-31",
  },
  {
    nome: "Aviosuperficie Enemonzo",
    urlFonte: null,
    comune: "Enemonzo",
    localita: null,
    provincia: "UD",
    tipo: "Aviosuperficie",
    categoria: "aviosuperficie",
    codice: null,
    icao: null,
    indirizzo: null,
    cap: null,
    lat: null,
    lon: null,
    quotaM: null,
    piste: null,
    categorieVolo: [],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: null,
  },
  {
    nome: "AVRO Rivoli di Osoppo",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/avro-rivoli-di-osoppo_UD03",
    comune: "Osoppo",
    localita: null,
    provincia: "UD",
    tipo: "Aviosuperficie",
    categoria: "aviosuperficie",
    codice: "UD03",
    icao: "LIKH",
    indirizzo: null,
    cap: "33010",
    lat: 46.234167,
    lon: 13.0725,
    quotaM: null,
    piste: 1,
    categorieVolo: ["General aviation", "Advanced UL", "Basic UL", "Gliders", "Helicopters"],
    enacDirezione: "Nord-Est",
    fascicolo: "5.1.8.1_2024_94",
    aggiornatoFonte: "2025-11-28",
  },
  {
    nome: "Cantina Turus",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/cantina-turus_GO03",
    comune: "Mossa",
    localita: null,
    provincia: "GO",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "GO03",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.923633,
    lon: 13.54035,
    quotaM: 51,
    piste: 1,
    categorieVolo: [],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-07-09",
  },
  {
    nome: "Casarsa della Delizia",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/casarsa-della-delizia_UD19",
    comune: "Casarsa della Delizia",
    localita: null,
    provincia: "PN",
    tipo: "Aeroporto militare (asfaltato)",
    categoria: "aeroporto-militare",
    codice: "UD19",
    icao: "LIDK",
    indirizzo: null,
    cap: null,
    lat: 45.953517,
    lon: 12.8178,
    quotaM: 38,
    piste: 1,
    categorieVolo: [],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2023-07-13",
  },
  {
    nome: "Chiasiellis Associazione Volo",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/chiasiellis-associazione-volo_UD13",
    comune: "Mortegliano",
    localita: null,
    provincia: "UD",
    tipo: "Aviosuperficie",
    categoria: "aviosuperficie",
    codice: "UD13",
    icao: null,
    indirizzo: null,
    cap: "33050",
    lat: 45.945556,
    lon: 13.207778,
    quotaM: null,
    piste: 1,
    categorieVolo: ["General aviation", "Advanced UL", "Basic UL"],
    enacDirezione: "Nord-Est",
    fascicolo: "5.1.8.1_2024_204",
    aggiornatoFonte: "2026-02-19",
  },
  {
    nome: "Enemonzo",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/enemonzo_UD05",
    comune: "Enemonzo",
    localita: null,
    provincia: "UD",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "UD05",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 46.404367,
    lon: 12.8853,
    quotaM: 373,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-02-19",
  },
  {
    nome: "FLY & JOY",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/fly-and-joy_UD11",
    comune: "Premariacco",
    localita: null,
    provincia: "UD",
    tipo: "Aviosuperficie",
    categoria: "aviosuperficie",
    codice: "UD11",
    icao: null,
    indirizzo: "Casali Pasch 1",
    cap: "33040",
    lat: 46.066944,
    lon: 13.370278,
    quotaM: null,
    piste: 1,
    categorieVolo: ["General aviation", "Advanced UL", "Basic UL"],
    enacDirezione: "Nord-Est",
    fascicolo: "5.1.8.1_2024_96",
    aggiornatoFonte: "2025-07-06",
  },
  {
    nome: "Fly Evolution",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/fly-evolution_UD15",
    comune: "Pavia di Udine",
    localita: "Selvuzzis",
    provincia: "UD",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "UD15",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.981967,
    lon: 13.30705,
    quotaM: 57,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-02-19",
  },
  {
    nome: "Flysynthesis",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/flysynthesis_UD14",
    comune: "Mortegliano",
    localita: "Lavariano",
    provincia: "UD",
    tipo: "Pista dismessa",
    categoria: "pista-dismessa",
    codice: "UD14",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.968683,
    lon: 13.23595,
    quotaM: 51,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2022-11-30",
  },
  {
    nome: "Gorizia",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/gorizia_GO01",
    comune: "Gorizia",
    localita: null,
    provincia: "GO",
    tipo: "Aeroporto civile (non asfaltato)",
    categoria: "aeroporto-civile",
    codice: "GO01",
    icao: "LIPG",
    indirizzo: null,
    cap: null,
    lat: 45.9075,
    lon: 13.6,
    quotaM: 59,
    piste: 2,
    categorieVolo: ["General aviation", "Advanced UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-07-09",
  },
  {
    nome: "I Grifoni",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/i-grifoni_UD08",
    comune: "S.Vito al Torre",
    localita: "Nogaredo al Torre",
    provincia: "UD",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "UD08",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.913383,
    lon: 13.3718,
    quotaM: 29,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2023-11-20",
  },
  {
    nome: "iCordovado",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/icordovado_PN01",
    comune: "Cordovado",
    localita: null,
    provincia: "PN",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "PN01",
    icao: null,
    indirizzo: "Via Vilunghi 12",
    cap: null,
    lat: 45.8365,
    lon: 12.89255,
    quotaM: 12,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-02-19",
  },
  {
    nome: "La Comina",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/la-comina_PN03",
    comune: "Pordenone",
    localita: null,
    provincia: "PN",
    tipo: "Pista dismessa",
    categoria: "pista-dismessa",
    codice: "PN03",
    icao: "LIKL",
    indirizzo: null,
    cap: null,
    lat: 45.991517,
    lon: 12.654317,
    quotaM: 66,
    piste: 2,
    categorieVolo: ["General aviation", "Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2025-11-18",
  },
  {
    nome: "Pasiano",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/pasiano_PN04",
    comune: "Pasiano",
    localita: null,
    provincia: "PN",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "PN04",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.832417,
    lon: 12.59335,
    quotaM: 6,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-05-14",
  },
  {
    nome: "Piancada",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/piancada_UD10",
    comune: "Palazzolo dello Stella",
    localita: null,
    provincia: "UD",
    tipo: "Aviosuperficie",
    categoria: "aviosuperficie",
    codice: "UD10",
    icao: null,
    indirizzo: null,
    cap: "33056",
    lat: 45.7644,
    lon: 13.072806,
    quotaM: null,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: "Nord-Est",
    fascicolo: "5.1.8.1_2024_296",
    aggiornatoFonte: "2025-08-27",
  },
  {
    nome: "Pravisdomini",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/pravisdomini_PN08",
    comune: "Pravisdomini",
    localita: null,
    provincia: "PN",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "PN08",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 45.82165,
    lon: 12.6835,
    quotaM: 7,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL", "Gliders"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-05-14",
  },
  {
    nome: "Rivolto",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/rivolto_UD16",
    comune: "Rivolto",
    localita: null,
    provincia: "UD",
    tipo: "Aeroporto militare (asfaltato)",
    categoria: "aeroporto-militare",
    codice: "UD16",
    icao: "LIPI",
    indirizzo: null,
    cap: null,
    lat: 45.98055,
    lon: 13.05,
    quotaM: 55,
    piste: 1,
    categorieVolo: [],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2023-07-13",
  },
  {
    nome: "Sassodoro",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/sassodoro_PN06",
    comune: "Sequals",
    localita: "Solimbergo di Sequals",
    provincia: "PN",
    tipo: "Campo volo",
    categoria: "campo-volo",
    codice: "PN06",
    icao: null,
    indirizzo: null,
    cap: null,
    lat: 46.181667,
    lon: 12.822233,
    quotaM: 238,
    piste: 1,
    categorieVolo: ["Advanced UL", "Basic UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-01-22",
  },
  {
    nome: "Trieste Ronchi dei Legionari",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/trieste-ronchi-dei-legionari_GO02",
    comune: "Ronchi dei Legionari",
    localita: null,
    provincia: "GO",
    tipo: "Aeroporto civile (asfaltato)",
    categoria: "aeroporto-civile",
    codice: "GO02",
    icao: "LIPQ",
    indirizzo: null,
    cap: null,
    lat: 45.8275,
    lon: 13.472217,
    quotaM: 11,
    piste: 1,
    categorieVolo: ["General Aviation", "Advanced UL"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-04-16",
  },
  {
    nome: "Trivignano",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/trivignano_UD09",
    comune: "Trivignano Udinese",
    localita: null,
    provincia: "UD",
    tipo: "Aviosuperficie",
    categoria: "aviosuperficie",
    codice: "UD09",
    icao: null,
    indirizzo: null,
    cap: "33050",
    lat: 45.931111,
    lon: 13.361111,
    quotaM: null,
    piste: 1,
    categorieVolo: ["General aviation", "Advanced UL", "Basic UL"],
    enacDirezione: "Nord-Est",
    fascicolo: "5.1.8.1_2024_269",
    aggiornatoFonte: "2025-06-13",
  },
  {
    nome: "Udine Campoformido",
    urlFonte: "https://webaai.it/it/aviostrutture/friuli_venezia_giulia/udine-campoformido_UD07",
    comune: "Pasian di Prato",
    localita: "Campoformido",
    provincia: "UD",
    tipo: "Aeroporto civile (non asfaltato)",
    categoria: "aeroporto-civile",
    codice: "UD07",
    icao: "LIPD",
    indirizzo: null,
    cap: null,
    lat: 46.0311,
    lon: 13.182783,
    quotaM: 93,
    piste: 1,
    categorieVolo: ["General aviation", "Advanced UL", "Gliders", "Helicopters"],
    enacDirezione: null,
    fascicolo: null,
    aggiornatoFonte: "2026-04-16",
  },];
